### Testowa nazwa drugiego requestu w oparciu o inny plik
POST http://{{host}}/status/{{ flow_test_1 }}
Accept: text/plain

> {%
    client.log('test2')
    client.test('rzeczywisty test, sprawdzam czy wartość została przekazana', function () {
        client.assert(response.status === 400, 'kod nie jest 400')
        client.assert(response.headers.valueOf('Access-Control-Allow-Credentials') === 'true', 'header test not passed')
    })
%}

