GET https://{{host}}/get
Accept: application/json

> {%
    client.test('rzeczywisty test, ma zwracać 200', function () {
        client.assert(response.status === 200, 'kod nie jest 200')
    })
%}

###

POST https://{{host}}/status/500
Accept: text/plain

> {%
    client.test('rzeczywisty test, ma zwracać 500', function () {
        client.assert(response.status === 500, 'kod nie jest 500')
    })
%}

###

POST https://{{host}}/status/200
Accept: text/plain

> {%
    client.test('rzeczywisty test, niby ma zwacać 400, ale zwraca 200, ma się wywalić', function () {
        client.assert(response.status === 400, 'kod nie jest 400')
    })
%}

