### Testowa nazwa drugiego requestu
GET http://{{host}}/anything/{anything}
Accept: application/json

{
    "filters": {
        "status": ["example1", "example2"],
        "cod": {
            "currency": "PLN",
            "amount": 100
        }
    },
    "type": ["test"]
}

> {%
    client.test('rzeczywisty test, ma zwracać 200', function () {
        let expectedBody = '{"filters[cod][amount]":"100","filters[cod][currency]":"PLN","filters[status][0]":"example1","filters[status][1]":"example2","type[0]":"test"}'
        client.assert(response.status === 200, 'kod nie jest 200')
        client.assert(response.contentType.mimeType === 'application/json', 'missing mime type')
        client.assert(JSON.stringify(response.body.args) === expectedBody, 'expects correct query string')
    })
%}
