// testowy request z błędem w teście
POST http://{{host}}/status/200
Accept: text/plain

> {%
    client.test('rzeczywisty test, nieistniejąca zmienna', function () {
        client.assert(aasdasda, 'nie istnieje')
    })
%}

###

// testowy request z nieistniejącą zmienną
POST http://{{ host }}/status/{{ nieistniejaca_zmienna }}
Accept: text/plain

> {%
    client.test('rzeczywisty test, nieistniejąca zmienna', function () {
        client.assert(true, 'false')
    })
%}

###

// testowy request z nieistniejącą zmienną
POST http://{{ host }}/status/200
Accept: text/plain
Authorization: Bearer {{nieistniejaca_zmienna}}

> {%
    client.test('rzeczywisty test, nieistniejąca zmienna', function () {
        client.assert(true, 'false')
    })
%}

### Testowa nazwa drugiego requestu
POST http://{{host}}/anything/{anything}
Accept: application/json

{
    "test": 400,
    "lastIdentifier": {{flow_test_1}}
}

> {%
    client.test('rzeczywisty test, nieistniejąca zmienna', function () {
        client.assert(true, 'false')
    })
%}
