### Testowa nazwa pierwszego requestu
POST http://{{host}}/anything/{anything}
Accept: application/json

{
    "test": 400
}

> {%
    client.global.set('flow_test_1', response.body.json.test)
    client.log('test')
    client.test('rzeczywisty test, ma zwracać 200', function () {
        client.assert(response.status === 200, 'kod nie jest 200')
        client.assert(response.contentType.mimeType === 'application/json', 'missing mime type')
    })
%}

###

### Testowa nazwa drugiego requestu
POST http://{{host}}/status/{{ flow_test_1 }}
Accept: text/plain

> {%
    client.log('test2')
    client.test('rzeczywisty test, sprawdzam czy wartość została przekazana', function () {
        client.assert(response.status === 400, 'kod nie jest 400')
        client.assert(response.headers.valueOf('Access-Control-Allow-Credentials') === 'true', 'header test not passed')
    })
%}

